name: Simple CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-16.04
        - ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Install mandatory prereqs
      run: sudo apt update -qy && sudo apt install -qy libdanga-socket-perl liblog-log4perl-perl libxml-libxml-perl libunicode-stringprep-perl libnet-dns-perl
    - name: Install test and plugin prereqs
      run: sudo apt install -qy make libtest-sharedfork-perl libtest-tcp-perl libdbd-sqlite3-perl libfile-slurp-perl libcgi-fast-perl nginx
    - name: Bootstrap
      run: perl Makefile.PL
    - name: Checkout parent repo
      uses: actions/checkout@v2
      with:
        repository: djabberd/DJabberd
        ref: master
        path: djabberd
    - name: Install DJabberd
      run: cd djabberd && perl Makefile.PL && make && sudo make install && cd ..
    - name: Build
      run: make
    - name: Test
      run: make test

